### ISSUE TITLE
Crash putting card of script function in item importer 'import all items slot'

### ISSUE THREAD

**Issue by milkev** [CyclopsMC/IntegratedScripting#9]
#### Issue type:

- :bug: Bug 

____

#### Short description:
just started messing around with integrated scripting. Was wanting to try a basic settup to read the nbt data of a Powah energizing orb and import/export items based on it. I made a basic function, and stuck it in the 'import items to network' slot in an inventory importer only for the server to crash
I am running with sinytra connector, im lazy and just want to play rn so im not gonna relaunch a bunch of times to test without it and stuff, just gonna go use the visual scripting cards.

I was able to log back into the world without it crashing, and just pulled the card out of the item importer.

#### Steps to reproduce the problem:

1. make function card
2. put it in the 'import all items slot' of an item importer

#### Expected behaviour:

1. not for it to work necessarily, but definitely for the server to not crash

____

#### Versions:

- This mod: 1.21.2
- Minecraft: 1.20.1
- Forge: 47.1.3

#### Log file:
crash log: [crash-2024-04-05_22.06.58-server.txt](https://github.com/CyclopsMC/IntegratedScripting/files/14892302/crash-2024-04-05_22.06.58-server.txt)
latest.log: [2024-04-05-1.log.gz](https://github.com/CyclopsMC/IntegratedScripting/files/14892310/2024-04-05-1.log.gz)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Note to self:

```
java.lang.ClassCastException: class org.cyclops.integrateddynamics.core.evaluate.variable.ValueTypeOperator$ValueOperator cannot be cast to class org.cyclops.integrateddynamics.core.evaluate.variable.ValueTypeList$ValueList (org.cyclops.integrateddynamics.core.evaluate.variable.ValueTypeOperator$ValueOperator and org.cyclops.integrateddynamics.core.evaluate.variable.ValueTypeList$ValueList are in module integrateddynamics@1.21.2 of loader 'TRANSFORMER' @34e0d52e)
	at org.cyclops.integratedtunnels.part.aspect.TunnelAspectWriteBuilders$Item.lambda$static$6(TunnelAspectWriteBuilders.java:653) ~[IntegratedTunnels-1.20.1-1.8.25.jar%231033!/:1.8.25] {re:classloading}
	at org.cyclops.integrateddynamics.core.part.aspect.build.AspectBuilder$BuiltWriter.write(AspectBuilder.java:396) ~[IntegratedDynamics-1.20.1-1.21.2.jar%231030!/:1.21.2] {re:classloading}
	at org.cyclops.integrateddynamics.part.aspect.write.AspectWriteBase.update(AspectWriteBase.java:58) ~[IntegratedDynamics-1.20.1-1.21.2.jar%231030!/:1.21.2] {re:classloading}
	at org.cyclops.integrateddynamics.core.part.aspect.build.AspectBuilder$BuiltWriter.update(AspectBuilder.java:419) ~[IntegratedDynamics-1.20.1-1.21.2.jar%231030!/:1.21.2] {re:classloading}
	at org.cyclops.integrateddynamics.core.part.write.PartTypeWriteBase.update(PartTypeWriteBase.java:90) ~[IntegratedDynamics-1.20.1-1.21.2.jar%231030!/:1.21.2] {re:classloading}
	at org.cyclops.integrateddynamics.core.part.write.PartTypeWriteBase.update(PartTypeWriteBase.java:57) ~[IntegratedDynamics-1.20.1-1.21.2.jar%231030!/:1.21.2] {re:classloading}
	at org.cyclops.integrateddynamics.core.network.PartNetworkElement.update(PartNetworkElement.java:168) ~[IntegratedDynamics-1.20.1-1.21.2.jar%231030!/:1.21.2] {re:classloading}
	at org.cyclops.integrateddynamics.core.network.Network.update(Network.java:409) ~[IntegratedDynamics-1.20.1-1.21.2.jar%231030!/:1.21.2] {re:classloading}
	at org.cyclops.integrateddynamics.core.TickHandler.onTick(TickHandler.java:74) ~[IntegratedDynamics-1.20.1-1.21.2.jar%231030!/:1.21.2] {re:classloading}
	at org.cyclops.integrateddynamics.core.__TickHandler_onTick_TickEvent.invoke(.dynamic) ~[IntegratedDynamics-1.20.1-1.21.2.jar%231030!/:1.21.2] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
```
